# -*- coding: utf-8 -*-
"""Guess the Number Game 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZdxbFBZBksujCH_b-3n3WQLgk24aaAEC
"""

import random

def generate_random_number():
    return random.randint(1, 100)

def get_player_guess():
    guess = input("Guess a number between 1 and 100: ")
    while not guess.isdigit():
        guess = input("Invalid guess. Please enter a number between 1 and 100: ")
    return int(guess)

def check_guess(guess, answer):
    if guess == answer:
        return "Correct!"
    elif guess < answer:
        return "Too low!"
    else:
        return "Too high!"

def play_game():
    answer = generate_random_number()
    guesses = 0

    print("Welcome to the Guess the Number game!")

    while guesses < 10:
        guess = get_player_guess()
        guesses += 1

        result = check_guess(guess, answer)

        if result == "Correct!":
            print("Congratulations! You guessed the number correctly in {} guesses!".format(guesses))
            break
        else:
            print(result)

    if guesses == 10:
        print("Sorry, you ran out of guesses. The correct number was {}.".format(answer))

if __name__ == "__main__":
    play_game()